# This workflow will build and test a golang project, including coverage
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test with Coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Print Coverage
      run: go tool cover -func=coverage.out
